### PR TITLE
React, Redux, SASS frontend

### PR DESCRIPTION
**Pull request by lilannie**
**DO NOT MERGE YET**
Here is an ongoing PR for the new frontend.

I am using React, Redux, and SASS.
I use Webpack to transpile and bundle the source code.

I then use a Node to serve the bundle.js file on `localhost:8080`

### CODE REVIEW

**Review by JMStudiosJoe — APPROVED** [review]
I would say looks good to me and ready for merge. Don't add more story related changes since will not have to do with the project setup of the frontend. We should keep branches clean to what they will be accomplishing.

**Comment by JMStudiosJoe** [comment]
@lilannie  Is this one ready to merge?

**Comment by lilannie** [comment]
Ready when u r! (:

Where can I find a list of the user stories? 
Do you usually create github issues for them?

**Comment by JMStudiosJoe** [comment]
I think the frontend issues discussion GitHub issue has the first draft of user stories, need to get those into a spreadsheet and shared with everyone. Yes, we usually would have an issue opened and then a PR for the feature when the code is ready.

**Pull request merged**
